### PR TITLE
Add I/O 2018 style.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Probably a bit late to add, but not if you're just starting your slides <sup>like <sup>me!</sup></sup>

**Comment by romannurik** [comment]
Hmmm, the contrast in this theme isn't quite right... is this intentional?

image

**Comment by JakeWharton** [comment]
I pulled the colors directly from the Keynote template deck but it does look more washed out from your image. Let me check the Google Slides colors.

**Comment by JakeWharton** [comment]
The hex colors are the same in Google Slides.

It's not as washed out for me locally:
screen shot 2018-05-01 at 3 05 53 pm

**Comment by romannurik** [comment]
Hrmm that contrast isn't very good :-/ probably too late to fix it though..

**Pull request closed without merging**
