### PR TITLE
Add Angular Material Color theme

### PR DESCRIPTION
**Pull request by twerske**
Add an Angular Material color theme for formatting code for decks following the styling of Angular Material.

This custom theme is currently used for all external slides by the Angular team at Google - so having a drop down option would be super helpful!

### CODE REVIEW

**Comment by romannurik** [comment]
Hi there! Two things:

1. This doesn't actually allow you to choose the color theme from the dropdown (you need to edit `index.html` for that)
2. What is this theme? Is this for decks for the Angular Material team? Some description might be useful :)

**Comment by twerske** [comment]
@romannurik sorry for the massive massive delay on this - 
I've updated the PR with the dropdown html and added a description. As on 2021+ this theme is the official external code styling theme of Angular's code snippets in slides, so it'd be great to be a dropdown!

**Comment by romannurik** [comment]
Hi there! Almost ready to merge! Just one piece of feedback:

- The contrast between regular text (F8F9FA) and comments (grey 300) is somewhat low ... can comments be a bit darker?
- The contrast between the dimmed color (grey 400) and comments (grey 300) is also somewhat low ... you may want to make dimme text *very* dimmed as it's normally part of a slide progression / legiiblity less important

But -- I leave this entirely up to you... happy to merge as-is if you prefer.

screenshot of the theme

**Comment by twerske** [comment]
Updated and addressed those colors - we're prioritizing visual simplicity over accessibility of unfocused content

**Comment by romannurik** [comment]
Looks great!

**Pull request merged**
